<!DOCTYPE html>
<html lang="pt-br"> 
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>AlphaIPTV</title>
        <link rel="stylesheet" href="<?php echo CSS; ?>inicial/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?php echo CSS; ?>inicial/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?php echo CSS; ?>inicial/css/style.css">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:600italic,400,800,700,300' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=BenchNine:300,400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="<?php echo JS; ?>inicial/js/modernizr.js"></script>
        <link rel="stylesheet" href="<?php echo CSS; ?>barras.css">
        <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

    </head>
    <body>

        <!-- ====================================================
        header section -->
        <header class="top-header" >
            <div class="container">
                <div class="row">
                    <div class="col-xs-5 header-logo">
                        <br>
                        <a href="index.html"><img src="<?php echo IMG; ?>inicial/img/logon.png" 
                                                  style="width: 150px; 
                                                  height: 90px;  
                                                  position: absolute; 
                                                  margin-top: -20px;" alt="" class="img-responsive logo"></a>
                    </div>

                    <div class="col-md-7">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid nav-bar">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">IPTV navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"style="width: 900px;">

                                    <ul style="margin-right: 150px;" class="nav navbar-nav navbar-right">
                                        <li><a class="menu active" href="<?php echo BASE; ?>" >Início</a></li>
                                        <li><a class="menu" href="<?php echo BASE; ?>produtos">Produtos</a></li>
                                        <li><a class="menu" href="#service">Sobre nós</a></li>
                                        <li><a class="menu" target="_blank" href="https://ws.nperf.com/partner/frame?l=3ae59686-4b09-4589-8fe6-c78922620a04">Teste sua Conexão</a></li>
                                        <li><a class="menu" href="#contact">Contate-nos</a></li>
                                        <li><a class="menu" href="<?php echo BASE; ?>login">Logar</a></li>
                                    </ul>
                                </div><!-- /navbar-collapse -->
                            </div><!-- / .container-fluid -->
                        </nav>
                    </div>
                </div>
            </div>
        </header> <!-- end of header area -->

        <section class="slider" id="home">
            <div class="container-fluid">
                <div class="row">
                    <div id="carouselHacked" class="carousel slide carousel-fade" data-ride="carousel"  style="margin-top: -31px;">
                        <div class="header-backup"></div>
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="<?php echo IMG; ?>inicial/img/car.jpg" alt="">
                                <div class="carousel-caption">
                                    <p>Luz, câmera, ação</p>
                                    <p>O melhor do cinema dentro de sua casa</p>
                                    <button>Confira...</button>
                                </div>
                            </div>
                            <div class="item">
                                <img src="<?php echo IMG; ?>inicial/img/car1.jpg" alt="">
                                <div class="carousel-caption">
                                    <p>Para a criançada</p>
                                    <p>Temos uma grande variedade de canais infantis</p>
                                    <button>Confira...</button>
                                </div>
                            </div>
                            <div class="item">
                                <img src="<?php echo IMG; ?>inicial/img/car2.jpg" alt="">
                                <div class="carousel-caption">
                                    <p>Procura aventura?</p>
                                    <p>Temos os mais diversos canais de filmes</p>
                                    <button>Confira...</button>
                                </div>
                            </div>
                            <div class="item">
                                <img src="<?php echo IMG; ?>inicial/img/car3.jpg" alt="">
                                <div class="carousel-caption">
                                    <p>Canais de Tv Fechada ou Aberta</p>
                                    <p>Temos uma ótima estabilidade de Canais</p>
                                    <button>Confira...</button>
                                </div>
                            </div>
                            <div class="item">
                                <img src="<?php echo IMG; ?>inicial/img/car5.jpg" alt="">
                                <div class="carousel-caption">
                                    <p>Estamos sempre a sua disposição</p>
                                    <p>Te auxiliaremos em tudo, somos o futuro, somos o agora somos Alpha.</p>
                                    <button>Confira...</button>
                                </div>
                            </div>
                        </div>
                        <!-- Controls -->
                        <a class="left carousel-control" href="#carouselHacked" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carouselHacked" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </section><!-- end of slider section -->

        <!-- about section -->
        <!-- script tags
        ============================================================= -->
        <script src="<?php echo JS; ?>inicial/js/jquery-2.1.1.js"></script>
        <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
        <script src="<?php echo JS; ?>inicial/js/gmaps.js"></script>
        <script src="<?php echo JS; ?>inicial/js/smoothscroll.js"></script>
        <script src="<?php echo JS; ?>inicial/js/bootstrap.min.js"></script>
        <script src="<?php echo IMG; ?>inicial/js/custom.js"></script>
    </body>
</html>