    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                    </a>
                </div>
                <div class="panel-body">
                    <h4 class="alert alert-success">
                        Uhull! Você foi autenticado com sucesso!
                    </h4>
                    <a href="<?php echo BASE . 'login/sair'; ?>" class="btn btn-danger">Sair</a>
                </div>
            </div>
        </div>
    </div>
