<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="author" content="Leonardo P. Vasconcelos">
        <meta name="generator" content="AlphaIPTV">
        <link rel="shortcut icon" href="<?php echo IMG; ?>Alpha.png" type="image/x-icon">
        <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
        <script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
        <?php
        echo $add_css;
        echo $add_js;
        ?>
    </head>
    <body>
